### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by joy002** [abijitj/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
   - Use backticks for code examples and not single quote('). For instance, `ls`, `pwd`, etc.
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
   - Include the counts of keystrokes needed to show run remotely saves time.
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Good job:)

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by abijitj** [comment]
Hello,

For the second to last bullet point, will it work to just add a sentence or two describing the number of keystrokes required previously and the number of keystrokes afterwards? To show the improvements. 

Sincerely,
Abijit J

**Comment by joy002** [comment]
Yes! And maybe include two or more sentence explaining why the # of keystrokes afterward is less than the # of keystrokes previously.

**Comment by joy002** [comment]
Hi, you forget to use backticks on `.ssh` and `scp` on second paragraph in part 5. Please leave me a comment after you fixed that!

**Comment by abijitj** [comment]
I changed it. Thank you for letting me know!

**Comment by joy002** [comment]
Nice! I have regraded your lab report, feel free to ask me if there is any questions!
